// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc9arAic2g3YlnSCjmzomffE4ajUD9q68',
    appId: '1:189991307395:web:c46c050490681edadb73b6',
    messagingSenderId: '189991307395',
    projectId: 'en-hanz',
    authDomain: 'en-hanz.firebaseapp.com',
    storageBucket: 'en-hanz.firebasestorage.app',
    measurementId: 'G-QKN25LWHZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8pZLHskC2Oyaw8VgZoPDYLP21x9FEGXA',
    appId: '1:189991307395:android:e4c6f4bb5b0f2c18db73b6',
    messagingSenderId: '189991307395',
    projectId: 'en-hanz',
    storageBucket: 'en-hanz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQM9K8kWoBiQ7eBKcjhshALUr9vhyGLME',
    appId: '1:189991307395:ios:cb1ab510fee579c9db73b6',
    messagingSenderId: '189991307395',
    projectId: 'en-hanz',
    storageBucket: 'en-hanz.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQM9K8kWoBiQ7eBKcjhshALUr9vhyGLME',
    appId: '1:189991307395:ios:cb1ab510fee579c9db73b6',
    messagingSenderId: '189991307395',
    projectId: 'en-hanz',
    storageBucket: 'en-hanz.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc9arAic2g3YlnSCjmzomffE4ajUD9q68',
    appId: '1:189991307395:web:b1407b4848a21d9adb73b6',
    messagingSenderId: '189991307395',
    projectId: 'en-hanz',
    authDomain: 'en-hanz.firebaseapp.com',
    storageBucket: 'en-hanz.firebasestorage.app',
    measurementId: 'G-80Y6YCVEFH',
  );
}
